version: 2
updates:
  - package-ecosystem: bundler
    vendor: true
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "21:00"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
