version: 2
updates:
  - package-ecosystem: bundler
    vendor: true
    directory: "/"
    groups:
      ruby-dependencies:
        patterns:
          - "*"
    schedule:
      interval: monthly

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
