inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - ".github/**/*"

Style/HashSyntax:
  Enabled: false

Style/WordArray:
  Enabled: false
